// src/pages/index.vue
<template lang="pug">
main(class="w-full flex flex-col justify-center min-h-screen text-center text-gray-800")
  img(class="rounded rounded-full h-50 w-50 mx-auto" src="https://avatars.githubusercontent.com/u/39351572?v=4")
  h1(class="m-0 text-gray-800 dark:text-gray-100") Vitor Daniel
  div(class="flex text-3xl gap-3 md:(text-2xl gap-2) mx-auto text-gray-800 dark:text-gray-100")
    a(href="https://github.com/vadolasi" target="_blank")
      IconMdi:github
    a(href="https://www.linkedin.com/in/vitor-daniel-b288a5158/" target="_blank")
      IconMdi:linkedin
    a(href="mailto:vitor036daniel@gmail.com")
      IconMdi:email
  div(class="flex flex-col md:flex-row gap-4 w-full md:w-2/3 lg:w-1/3 mx-auto px-2 mt-10")
    NuxtLink(to="/blog" class="transition ease-in-out no-underline w-full md:w-1/2 p-2 border border-gray-800 rounded rounded-lg text-gray-800 dark:(border-gray-100 text-gray-100) hover:(bg-gray-800 text-gray-100) dark:hover:(bg-gray-100 text-gray-800)") Blog
    NuxtLink(to="/portfólio" class="transition ease-in-out no-underline w-full md:w-1/2 p-2 border border-gray-800 rounded rounded-lg text-gray-800 dark:(border-gray-100 text-gray-100) hover:(bg-gray-800 text-gray-100) dark:hover:(bg-gray-100 text-gray-800)") Portfólio
</template>

// pages/index.tsx
import type { NextPage } from "next"
import Image from "next/image"
import profilePic from "../public/me.jpeg"
import GithubIcon from "~icons/fa/github.jsx"
import LinkedinIcon from "~icons/fa/linkedin-square.jsx"
import EmailIcon from "~icons/fa/envelope.jsx"
import TelegramIcon from "~icons/fa/telegram.jsx"
import Icon from "../components/Icon"
import DefaultLayout from "../layouts/default"
import Link from "next/link"

const Home: NextPage = () => {
  return (
    <DefaultLayout>
      <Image
        src={profilePic}
        alt="Picture of the author"
        width={200}
        height={200}
        placeholder="blur"
        className="rounded-full"
      />
      <h1 className="m-2 text-3xl lg:text-4xl tracking-tight font-extrabold text-gray-900 dark:text-white">Vitor Daniel</h1>
      <p className="font-light text-gray-500 sm:text-xl dark:text-gray-400 mb-8">Desenvolvedor</p>

      <div className="flex text-2xl mt-5 gap-1">
        <Icon link="https://github.com/vadolasi" text="Github">
          <GithubIcon />
        </Icon>
        <Icon link="https://www.linkedin.com/in/vitor-daniel-b288a5158" text="Linkedin">
          <LinkedinIcon />
        </Icon>
        <Icon link="mailto:vitor036daniel@gmail.com" text="Email">
          <EmailIcon />
        </Icon>
        <Icon link="https://t.me/vadolasi" text="Telegram">
          <TelegramIcon />
        </Icon>
      </div>

      <p className="mt-5 text-lg font-normal text-gray-500 sm:px-16 xl:px-48 dark:text-gray-400">Visite meu <Link href="/blog"><a className="font-medium text-blue-600 dark:text-blue-500 hover:underline">blog</a></Link></p>
    </DefaultLayout>
  )
}

export default Home
